/**
 * Every company the portal can wear.
 *
 * The launcher lists these. Which one is ACTIVE is decided by the facades in
 * src/data — regenerated by `npm run company:<id>` — because the data layer is
 * imported statically across eighty-odd sites and the honest way to swap it
 * is to swap what those imports resolve to, not to thread a context through
 * every screen.
 */
export interface CompanyEntry {
  id: string;
  company: string;
  industry: string;
  pitch: string;
  /** Card artwork: the dark-cut lockup. */
  logo: string;
  logoHeight: number;
  /** Rail colour, for the card's accent. */
  accent: string;
  /** Where this company's build lives when it is not the active one. */
  url?: string;
}

export const COMPANIES: CompanyEntry[] = [
  {
    id: "fossil",
    company: "Fossil Group",
    industry: "Watches & accessories · licensed brands · FOB Asia",
    pitch: "Eight licensed and owned watch calendars through three regional DCs — the original build.",
    logo: "/companies/fossil/fossil-logo.svg",
    logoHeight: 20,
    accent: "#2a211c",
    url: process.env.NEXT_PUBLIC_COMPANY_URL_FOSSIL,
  },
  {
    id: "allison",
    company: "Allison Transmission",
    industry: "Commercial vehicle driveline · automatic transmissions",
    pitch: "The finished-unit book behind five plants and three distribution centres — components in, transmissions out to OEM programmes and the distributor channel.",
    logo: "/companies/allison/allison-transmission-full.svg",
    logoHeight: 22,
    accent: "#2360A5",
    url: process.env.NEXT_PUBLIC_COMPANY_URL_ALLISON,
  },
  {
    id: "target",
    company: "Target",
    industry: "Mass-market retail · owned & partner brands",
    pitch: "Owned-brand home and grocery flowing from Asia and domestic co-packers through three RDCs.",
    logo: "/companies/target/navanta-logo.svg",
    logoHeight: 22,
    accent: "#1d4a86",
    url: process.env.NEXT_PUBLIC_COMPANY_URL_TARGET,
  },
];

export function companyById(id: string): CompanyEntry | undefined {
  return COMPANIES.find((c) => c.id === id);
}
