#!/usr/bin/env node
/**
 * Point src/data at one company pack.
 *
 *   node scripts/select-company.mjs fossil|allison|target
 *
 * Every module in src/companies/<id>/data gets a one-line facade in src/data
 * that re-exports it, so the eighty-odd `@/data/...` imports across the app
 * resolve to that pack without a single component changing. Packs import each
 * other RELATIVELY (./catalogue), so an inactive pack is never pulled in.
 */
import { readdirSync, writeFileSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const id = process.argv[2];
const packDir = join(root, "src/companies", id ?? "", "data");
if (!id || !existsSync(packDir)) {
  console.error(`usage: select-company <id>  (packs: ${readdirSync(join(root, "src/companies")).filter((d) => !d.includes(".")).join(", ")})`);
  process.exit(1);
}
const out = join(root, "src/data");
rmSync(out, { recursive: true, force: true });
mkdirSync(out);
const modules = readdirSync(packDir).filter((f) => f.endsWith(".ts")).map((f) => f.replace(/\.ts$/, ""));
for (const m of modules) {
  writeFileSync(join(out, `${m}.ts`), `// Generated by scripts/select-company.mjs — do not edit. Active pack: ${id}\nexport * from "@/companies/${id}/data/${m}";\n`);
}
writeFileSync(join(out, ".active"), id + "\n");
console.log(`src/data → ${id} (${modules.length} modules)`);
